### ISSUE TITLE
ValueError: dataset_name should be specified but got None

### ISSUE THREAD

**Issue by bydmiller** [LLM360/amber-data-prep#1]
### Description:
When running the script convert_dataset_hf_refinedpajama_json.py, I encountered a __ValueError__ indicating that dataset_name should be specified but got None. This error occurs at line 200 in the script.

### Command Used:

```bash

python convert_dataset_hf_refinedpajama_json.py \
  --input_root ./ \
  --out_root refinedpajama_llama_json \
  --concat_tokens 2049 \
  --tokenizer huggyllama/llama-7b \
  --num_workers 64 \
  --eos_text '</s>'
```

### Code Causing the Error:

```python

hf_dataset = hf_datasets.load_dataset(
    path=dataset_name, data_dir=sub, split=split, streaming=True
)
```
Here is the full error gist: https://gist.github.com/sukhmancs/c6926e7b95551609f4a36c90e4cbb853

It seems that the dataset_name variable is not being properly initialized or passed to the load_dataset function, resulting in the error.

Thank you.

**Comment by TianhuaTao** [comment]
Hi! It seems you are using the latest version of `datasets` library. The latest version changed its behavior of `load_dataset` when using `path` and `data_dir`.

What you are running is actually:
```python
hf_dataset = hf_datasets.load_dataset(path="./", data_dir="redpajama_v1/arxiv", split='train', streaming=True)
```

In the latest version, the `datasets` will try to extract `dataset_name` from `path="./"` and the result is `None`. (Which is not the case for previous versions).

As a workaround, you can try to alter the line to be:
```python
hf_dataset = hf_datasets.load_dataset(path="./redpajama_v1/arxiv", split='train', streaming=True)
```
And the extracted name will be `arxiv`.

To fix it in code, you can change line 200 to be:
```python
hf_dataset = hf_datasets.load_dataset(
        path=os.path.join(dataset_name, sub), split=split, streaming=True
    )
```
Hopefully this should work.
